default_language_version:
  python: python3.11

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.7
    hooks:
      - id: ruff
        args: [ --fix ]

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        types: [python]

  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort
        language: system
        types: [python]
        args: [--profile=black]

  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: 'v1.10.0' 
  #   hooks:
  #   -   id: mypy
  #       args: [--strict, --ignore-missing-imports]